### ISSUE TITLE
RFC: 2023 Q3 Product engineering community plan

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#114]
## Mission

"Make PostHog a hub for product engineers to learn from and collaborate with each other" 

## Existing solutions/communities where product engineers go

- Hacker news
     - Not focused on product eng
- Hackernoon 
     - Not focused on product eng
- [Taro](https://www.jointaro.com/)
     - Career advice for big tech engineers
- Reddit
     - Handful of swe communties. None with a product eng focus.

## Current state of PostHog w.r.t. Product eng

Our blog and newsletter is well known for it's quality and our blogs get noticed. We have a good habit of publishing high quality articles with a regular cadence. However, this is one way communication and is _broadcasted_ from us. There is no real "community" yet. 

Here are the gaps to address in order to turn into a "hub" or "community":

- Give members the opportunity to _regularly_ engage with us, the content, and each other.
- Group content into themes, and make it easily searchable so that it's easy to find education on specific topics e.g., finding PMF, running A/B tests, etc.,

## Which platform for our community?

Where will our community members interact with each other? We should only choose one:

- **our website (recommended)**
     - Pros: Full control of the experience. Can integrate well into our website.
     - Cons: need to build a "feedback loop" i.e., we need our members to build a habit of getting people to check the website regularly, otherwise it may have poor engagement.
          
- **Slack**
     - Pros: People regularly open and Slack
     - Cons: Confusion with our existing Slack community (which has a customer support focus). Information gets easily lost. Hard to find the quality information from all the messages.
         
- **Reddit**
     - Pros: For established reddit users, it's already a habit to check it frequently, so feedback loop is already built in. Good for helping non-posthog users discover it
     - Cons: Alienates none reddit users. We don't "own" our community

- Any other platform:
       - Cons: If it's a new app, we still need to build the feedback loop. We wont have full control over the experience.

## Next steps

Chatted with @corywatilo on the below. W+D team is tackling this (and shipping fairly soon!)
(~~We should first enable our members to interact with each other. Ideas to do this are:~~
1. ~~Add commenting/reacts/upvoting to our blog content.~~
2. ~~Ensuring there's a good feedback e.g., emails when someone responds to your comments.~~
3. ~~Building on 1), we could also add a concept of "reputation" or "karma" (like Stack overflow or HN)~~

~~**My suggestion for Q3 is to focus on 1.) first**~~

~~We can then begin to think about other ideas, such as grouping our content or tackling themes of content~~

## Growing the community

A few ideas to grow the community, aside from regularly publishing our own content:

- PostHog startup program
    -  Make sure that in our 
    - To grow the startup program and/or community, we could offer to do a "marketing boost" for our members e.g., if they launch a new product, we can tweet about it, include it in our newsletters etc.

- We can do guest posts/interviews/discussions/youtube videos with knowledge people in the industry and cover product eng related topics. This helps us tap into their existing communities (and they tap into ours). It also helps create valuable content for our community

**Comment by Lior539** [comment]
> Add commenting/reacts/upvoting to our blog content.
Ensuring there's a good feedback e.g., emails when someone responds to your comments.
Building on 1), we could also add a concept of "reputation" or "karma" (like Stack overflow or HN)

Chatted with @corywatilo yesterday on this. It's a lot of what's on their roadmap, and will be added fairly soon! So I think best to leave this with the W+D team 

> We could do that any time – unified auth between https://github.com/PostHog/posthog.com/issues/5847 is only the blocker, imo. Comments and voting etc. is obviously important, but more of a nice-to-have in comparison.

@andyvan-ph can add elaborate on why you think this is a blocker? Not sure I follow the reasoning why merging the logins is so important.

> Like the idea of connecting with other people / companies who evangelise the product engineering idea. Could we do something like Startup Spotlight but for product engineers – e.g. we find product engineers, ask them about what they're working, how they work, how they went from engineer to product engineer etc.? Big reach is a bonus not a necessity, imo – there's value in reaching smaller groups of highly-engaged people, and they're be more grateful / interested in the exposure.

Yeah I think this is a great idea. Im quite excited by this

> Could we create the first / definitive product engineering survey?

Interesting! Will give it some thought, although my first instinct is that we're too early for this right now
> I really like the idea of reading lists for product engineers – James is already kind of working on something along these lines. Curated reading lists that's a mixture of our content + other people's content.

@corywatilo walked me through this too! Really nice idea

**Comment by andyvan-ph** [comment]
> @andyvan-ph can add elaborate on why you think this is a blocker? Not sure I follow the reasoning why merging the logins is so important.

Slack worked because most people already have a Slack account. There's no friction. The website forum currently requires you to create a separate account, which add an annoying friction point. Also doesn't support logging in via Google, GitHub etc., which might be a good solution as well.

Basically, if we want to kill Slack permanently, it needs to be as easy to ask a question in the forum as it is on Slack. Having a single login would do that.

**Comment by joethreepwood** [comment]
I agree with some places where this has ended up, but I think we need to take this back a step before trying to strategize this. Creating a community is not an engineering problem and I worry that we'll fail if we don't realize that. 

For example, we shouldn't start by considering the pros and cons of the platforms where _we_ want to to be. We should start by considering what _our users_ want.  

What our users want, I think, is to **discover useful information about making their products successful**. 

We do well at this the first part of this, because we're able to create a lot of content to this purpose. We hear often that our content is great and we see it creates good results. The main way we can get stronger is by centralizing the way content comes together and providing a way for users to engage back -- which is exactly what W&D team is already leading. 

The next question, in my opinion, should be _What do we want our community to be?_ This is a really important question and should be the main thing that shapes our strategy. Do we want our community to just be a place where users get a better tech support experience, or do we want it to be more? Do we want an exclusive, gated community or is it open to everyone? What sort of engagement do we want to encourage and what identifying characteristic should unite our community?

Answers to this question are what separate subreddits from Slack threads from Twitter from HackerNews. 

I'd argue that we want our community to be **the default location for product builders to share and get advice**. It shouldn't be just focused on PostHog and it should be high-value, such that it encourages word of mouth and meets the user need. 

I think the startup program is the best place to achieve this, in part because we know we can tie it directly to revenue and we can make it high-value by focusing in on particular types of users. We won't achieve a community just by having a tech support forum and adding comments to articles, but we might do it if we take a subset of our audience and invest in providing them opportunities to engage and connect. I put down [some thoughts on this](https://github.com/PostHog/company-internal/issues/1062#issuecomment-1604025604) before my holiday, but there's a lot more we can do to explore it.

**Comment by andyvan-ph** [comment]
> What our users want, I think, is to **discover useful information about making their products successful**.

Agree.

> I'd argue that we want our community to be **the default location for product builders to share and get advice**.

Agree.

> I think the startup program is the best place to achieve this, in part because we know we can tie it directly to revenue and we can make it high-value by focusing in on particular types of users.

Partial agree. I think the people in it could become our most engaged community members, but it isn't the whole community.

## Next steps

To keep things moving, I'm going to summarize what I think is the consensus. If anyone strongly disagrees with the following, please say so:

1. Most community activity will/should happen on the website, not Slack
2. Our ultimate goal is to be a hub of knowledge for all product engineers, not just PostHog users
3. We'll know we've been successful when people are sharing knowledge with each other independently
4. We should use the startup program to create highly-engaged community members

If we can agree on all those, I think: 

1. We can use this issue a little longer to throw around ideas for things we can do
2. We should have a mega issue for stuff we're actually going to do. Between Lior and Joe we could fill it with a few things already.

**Comment by joethreepwood** [comment]
All sounds good. I'd counter that I see an important distinction between _audience_ and _community_, but lets move forward and not split my remaining few hairs. 

I have a few ideas for improving the startup program [here](https://github.com/PostHog/company-internal/issues/1062#issuecomment-1604025604).

Ones we can do especially quickly, to get things moving: 

- Get the startups program into wider circulation, on other accelerators and partnerships
- Increase the visibility of the startup program across the site
- Create a calendar of potential events we can run for users in the audience

**Comment by ivanagas** [comment]
> Random ideas:
> 
> * Use forum to do AMAs on product engineering / startup topics – like Reddit, the key point here is they would be async experiences we can turn into content later. Could be with PostHog people, or other if they're sufficiently compelling.
> * Create specific forums / channels for topics – basically sub-reddits where people can talk about specific problems (e.g. how do I improve rentention). We probably need to create some kind of distinction between support forums for specific products / features and community ones. Maybe we should have "community chat" forum category?

These are good ideas. Drive usage of community questions beyond just support questions.

**Comment by Lior539** [comment]
Agree with everything that @joethreepwood and @andyvan-ph mentioned.  I think it's also important to call out that the W+D team is already working on a lot of this stuff to make posthog the default hub to PEs. The only gap that they're not focused on is the startup program.

> I think the startup program is the best place to achieve this, in part because we know we can tie it directly to revenue and we can make it high-value by focusing in on particular types of users

@joethreepwood would love to brainstorm with you on ideas and figure out a concrete plan

**Comment by joethreepwood** [comment]
Have thrown a calendar invite in for Monday, when we're all in the same place.
