### ISSUE TITLE
Messaging: Refund comms for duplication incident

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#128]
# Messaging

We charged approximately 85 customers more than we should as a result of a duplication incident. No users were charged more than $36. We've fixed the issue, done a refund, and are running a comm to tell them via email. 

[Cohort of impacted users. ](https://app.posthog.com/cohorts/45347)

Draft below. 

<img width="971" alt="Screenshot 2023-08-29 at 19 21 28" src="https://github.com/PostHog/meta/assets/84011561/27343172-9e79-4bc5-b892-9be5589bf356">

**Comment by joethreepwood** [comment]
All set up and ready to go with an approval from @raquelmsmith - I'll allow some time for others to feed in if they wish before scheduling. 

We could consider a more corporate tone, but better to keep this simple given the low stakes IMHO.

**Comment by raquelmsmith** [comment]
> No users were charged more than $36.

We actually can't be confident about this because of what I mentioned in Slack, the printed amounts were not correct. So while no customers were refunded very much, I think we can just say something like "most users were overcharged by $35 or less" to give us a bit of wiggle room.

> We've credited your account because we got something wrong

This sounds a bit... severe? Formal? Ambiguous? Something? Maybe something like "Whoops! We charged you for duplicate events, so we've credited your account."

Content:

Prob start off with "we have good news and bad news." Just starting with "the bad news" feels like something to contextualize is missing, and I'm wondering if there is good news or if it's all bad news. Or just remove words about "bad" and say "hey, we accidentally duplicated events and charged you for them, so we're making it right."

It was really a 2-day period but you can say 5 if you want?

Their bank balance won't be back to normal, because we credited their account, we did not refund them. That means their bill next month will be less the amount that they were overcharged.

**Comment by joethreepwood** [comment]
Yeah, fresh eyes in the morning lead me to agree. Here's a V2: 

<img width="843" alt="Screenshot 2023-08-30 at 10 43 17" src="https://github.com/PostHog/meta/assets/84011561/410a8b57-34aa-439b-ac9b-0d7840ef1d4b">

I'll schedule this now for Thursday 16:00 UTC, so let me know before then if further feedback!

**Comment by raquelmsmith** [comment]
> 2 day period
I prefer this with a hyphen - `2-day period`

> Most users were charged an extra $35
Nope, most users were overcharged _less than_ $35. Most were overcharged by $1-5.

> refunded you for the extra amount
> bank balance should now be back to normal
We did not refund, we credited their account. "We've added a credit to account, so you'll pay less on your next bill."

**Comment by joethreepwood** [comment]
<img width="747" alt="Screenshot 2023-08-30 at 17 58 23" src="https://github.com/PostHog/meta/assets/84011561/be8d66d5-dd4a-4b7a-838f-b2f109b4664b">

I clearly did not have my coffee this morning. Should have caught 2 of those at least. Sorry, but all fixed now.

**Comment by raquelmsmith** [comment]
Looks great! Thanks @joethreepwood!
