### ISSUE TITLE
Messaging: Surveys site app migration

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#134]
# Messaging

### Context
Surveys users are moving off of the site app, on to the JS SDK for launch. No action required, but it's nice to be given a heads-up!

### Goal
No goal we can track here. 

### Format
1x email 

### Audience / Targeting
@neilkakkar will share (over Slack) a list of emails we need to hit with this message. 

### Resources, timeline, responsibilities
We'll send this week, ASAP. 

### Requested input
Feedback on (incoming) copy.

**Comment by joethreepwood** [comment]
@neilkakkar Curious if best to target by Org, or individual user here?

If Org, I need Org_Ids. If individual, I need specific emails.

**Comment by neilkakkar** [comment]
oh, I didn't know you can easily target by org_ids - orgs would indeed be better, will send those instead!

**Comment by joethreepwood** [comment]
> oh, I didn't know you can easily target by org_ids - orgs would indeed be better, will send those instead!

Yep, though I try to avoid it for very long lists [due to this bug. ](https://github.com/PostHog/posthog/issues/17242)

Org IDs mean I have to create a cohort first. Emails I can just import into Customer.io. As long as it's less than 200 teams, Org_ID is fine.

**Comment by neilkakkar** [comment]
I have good news, the bug is no more 😋

**Comment by neilkakkar** [comment]
Ah, just realised I missed something important: people not using the snippet can be on an old version of posthog-js where this doesn't work, so the upgrade path needs to be more manual for them - otherwise we'll break surveys - I shouldn't disable the site app for them 😬.

Hmm, now wondering if the automation is more trouble than it's worth here. (cc: @liyiy ). I think I'll add a banner in app to tell them the upgrade path as well, but should mention it in the email too:

So, new doc (sorry @joethreepwood ):

Surveys require posthog-js version 1.81.1 to work.

1a. If you're using the snippet, you can just toggle on surveys on the surveys page and everything will work fine.
1b. If you're using a package manager, you should update posthog-js to 1.81.1 and then enable surveys in app.

2. You can then disable the "surveys app" app which will shortly be deprecated.

**Comment by liyiy** [comment]
I think as long as we are consistent everywhere and clear with saying "Surveys is being deprecated off of the site app. If you're using posthog-js through package manager, upgrade to version 1.81+ instead"

Since users already have to edit their posthog init with `opt_in_site_apps` in the original experience, it should be fine having them update. Definitely more annoying than an automatic transition but better to do it now than later when there's even more users!

**Comment by joethreepwood** [comment]
<img width="678" alt="Screenshot 2023-09-26 at 18 26 41" src="https://github.com/PostHog/meta/assets/84011561/f32dc88f-d9a3-4aa3-81ee-f34c418ecfe4">

Better?

**Comment by joethreepwood** [comment]
I chose the Oct 9th deadline to coincide with other surveys announcements. Important to give a deadline here, I feel.

**Comment by neilkakkar** [comment]
Does re-enable surveys link to `app.posthog.com/surveys` ? And Oct 9 is good - good call to be explicit with dates here 👍 .

One edit: Update posthog-js to _at least_ version 1.81.1 & then re-enable surveys.

---

And yes, much better, thank you!

**Comment by joethreepwood** [comment]
> Does re-enable surveys link to `app.posthog.com/surveys` ? 

It does

**Comment by joethreepwood** [comment]
<img width="686" alt="Screenshot 2023-09-26 at 18 33 00" src="https://github.com/PostHog/meta/assets/84011561/a1aaf52b-d185-4058-a416-247f0951c6c8">

Amended

**Comment by joethreepwood** [comment]
<img width="411" alt="Screenshot 2023-09-27 at 10 07 30" src="https://github.com/PostHog/meta/assets/84011561/6dfa947f-b9a3-4d25-8d52-f311e11e912e">
