### ISSUE TITLE
Messaging: App Deprecations

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/meta#153]
# Messaging

### Context

https://github.com/PostHog/product-internal/issues/488#issuecomment-1820923680

We're deprecating all of the following apps, and need to email users to tell them about it. 

- First time event tracker
- Event Sequence Timer
- Property Flattener
- Advanced GeoIP
- Unduplicator

The reasons for doing this are clear, in the issue linked above. 

### Needed info

I need three bits of info for each app: Alternative, Deadline, and Users. 

Alternative-wise, can you confirm if any of this is incorrect @tiina303 ?

- First time event tracker: Users should use HogQL. We don't have docs for this.
- Event Sequence Timer: Users should use HogQL. We don't have docs for this. 
- Property Flattener: Users should use HogQL. We don't have docs for this. 
- Advanced GeoIP: Users should use the GeoIP plugin and remove properties with the Property Filter app if needed. 
- Unduplicator: Users should set the UUID for every event they send. Do we have docs for this?

Date-wise, I'd say we should give users at least 14 days notice from when we send the emails. 

User-wise, I can pull the users in PostHog based on who has installed each app. We'll email everyone in each team. Let me know if there's a better way to do this. 

### Goal
We'll send 1x email to users for each app, ASAP. 

Once above is confirmed, I'll start building.

**Comment by tiina303** [comment]
unduplicator: I've explained it https://github.com/PostHog/posthog/issues/17211 (we're not going to add a separate idempotency key - uuid is exactly that key in combination with the other fields I listed there).

cc @mariusandra  for HogQL docs

> We'll send 1x email to users for each app, ASAP.

could we send a single email for all apps they use (I suspect many of these folks use many of these apps)

> User-wise, I can pull the users in PostHog based on who has installed each app. We'll email everyone in each team. Let me know if there's a better way to do this.

you can get the orgs here by app usage (not sure if better):

EU: http://metabase-eu/question/124-processevent-functions-in-eu
US: http://metabase-prod-us/question/381-processevent-usage

**Comment by mariusandra** [comment]
CC @benjackwhite for overall coordination.

> Date-wise, I'd say we should give users at least 14 days notice from when we send the emails.

Regarding the first time event tracker and event sequence timer. In essence all of these are replaceable with "queries", but some of the changes required are quire complex, some might essentially not be possible, and/or need support and workarounds by our team. As a customer, if this (PostHog) is a system I set up 2 years ago that's been running fine, and I get a mail of large breaking changes that will take effect 14 days from now, requiring a day of my time to mitigate, I'd be "mildly annoyed". We should properly analyse the impact before we do anything. It could be nothing, or it could be a lot of angry customers. It could also be a lot of sudden support work that's dumped on tea, product analytics the moment the mail goes out 🙃.

The JSON property flattener can be replaced with queries now, but array access with JSON is still kind of blergh. Ideally we'd do some improvements, but I don't see blockers.

Could we split this out, and do a trial run with the plugins that we know are safe to remove? Starting with Advanced GeoIP, Unduplicator and/or Property Flattener. Those are the easier ones to mitigate, but even then I'd still give a longer timerange than 14 days.

The HogQL docs for mitigating the tracker plugins to queries will take some time to write (to get started) if it's on our team, as we're heads down in some other work right now. 🤔

**Comment by joethreepwood** [comment]
I'm always happy to give users _more_ warning and time to make changes. 14 days is very much a minimum from my POV, so I'll really defer to you all on this.

**Comment by tiina303** [comment]
Just to state the obvious: from a pipeline and app stability perspective we'd love this to get done sooner rather than later (yes these plugins could take down the whole PostHog app for everyone).

Also agree that it's trickier to migrate for the first three apps. However I do think it's useful to send the email about all the apps together (more convenient for the user to see a single deprecation and do it at once rather than a deprecation every month) and the best way to get feedback is to try it out. So here's my proposal:
1. we send the deprecation email out (about all of these apps) to a small subset of users (e.g. N=10) as a test to see how it goes (starting with free and newer users) & see what feedback we get, based on which we can write HogQL docs for the first 3. I'd stick with the 14 days timeline - no-one ever starts doing anything before a couple of days before anyway and a deadline around Christmas wouldn't work at all.
2. repeat (1) until done

**Comment by joethreepwood** [comment]
I'm generally against wanting to stagger this announcement. I feel like it would be unlikely to give us any new information, and would create a lot more complexity to the process. I'd _much_ rather send an email with a longer deadline -- say a 30 days deadline -- and ask users to get in touch if they have questions. We can always push the deadline back, but this doesn't feel like an instance where a test is going to tell us much we don't/can't already know.

**Comment by tiina303** [comment]
> would create a lot more complexity to the process

yup I realize how this would be a bit more annoying :( 

> this doesn't feel like an instance where a test is going to tell us much we don't/can't already know.

it does to me, as essentially for the 1-3 apps we don't really know what problems users would run into & so having some docs ready after some initial feedback can help not kill product analytics with support requests.

**Comment by joethreepwood** [comment]
Isn't it likely to just protract the process though? 

Say we divide the group into three batches, and each needs 30 days. We'd have to collect and solve problems after each batch, likely delay multiple times, and spend a minimum of three months on it. 

If speed is of the essence it would seem a lot quicker to do one message with 30 days warning. Even if we end up pushing that back by another 30 days it still ends up faster.

Obviously I'm simplifying and will defer, but ripping the band-aid off at once would seem the way to go.

**Comment by tiina303** [comment]
First off I agree that we haven't found the best approach here yet.

> We're talking about 300ish users here

The migration story for advanced geoIP and unduplicator is clear and those issues would also go to pipeline team.

Aside from that we have:
In the US 286 of which (some orgs use multiple plugins):
145: First Time Event Tracker
84: Property Flattener Plugin
74: First Event Today (note that this was missing from the issue at the top)
46: Event Sequence Timer Plugin

In EU 63 of which:
35: First Time Event Tracker
18: Property Flattener Plugin
14: Event Sequence Timer Plugin

> someone who feels passionately about this goes through every impacted user by hand

This doesn't feel practical nor likely to ever happen, am I wrong?

Hence my question is there some way we can get this off the ground without that (maybe there's just very limited number of users who care about this? maybe there's very limited use cases users care about? Feels easier to ask them rather than analyse the impact of each user by hand, am I wrong?)
1. Can we send an email with softer language asking people to stop using the app or tell us what they need it for etc
1. Can we talk to customers in slack & say that we're looking to deprecate it & ask what they need from it & start from there? 1. Can we use surveys on the app for folks who uses one of the 4 apps to ask if they would be sad if would be killed and what they need for?

**Comment by joethreepwood** [comment]
I feel like the simplest path here may be identifying which of the users are high-prio/paying, then CS + Pipeline reaching out to them directly via Slack to discuss and understand impact for as many of them as possible. Based on this Docs and recommendations can be made for other users, and we can care for thos high-prio customers properly. 

Once the docs are updated, we can run an email comm to all impacted users and deal with edge-cases from there, delaying if needed.

**Comment by mariusandra** [comment]
> > someone who feels passionately about this goes through every impacted user by hand
> 
> This doesn't feel practical nor likely to ever happen, am I wrong?

This sounds like 2-4h of work to me, which seems worth it to not have 300ish angry customers. Probably just 1h if we only look at the high-prio customers, and after about 20 cases you'll likely see a very repeating pattern and things will go fast.

> Hence my question is there some way we can get this off the ground without that (maybe there's just very limited number of users who care about this? maybe there's very limited use cases users care about? Feels easier to ask them rather than analyse the impact of each user by hand, am I wrong?)
> 
> 1. Can we send an email with softer language asking people to stop using the app or tell us what they need it for etc
> 2. Can we talk to customers in slack & say that we're looking to deprecate it & ask what they need from it & start from there?
> 3. Can we use surveys on the app for folks who uses one of the 4 apps to ask if they would be sad if would be killed and what they need for?

It take as long, if not more, to build any of the above and then to analyse the results. I don't think this is practical/viable at all.

I'm most concerned that we'll find cases that are just not possible with the current system, and won't have time to build workarounds. Just telling users "suck it", even if with polite words, is not great.

We're asking people to change their queries, but we don't even know the impact nor if the changes are feasible/possible?? How is this a thing? Can we PLEASE slow down and figure out if any of this is even possible?

I'd be happy to help, but, this is super sudden, and I can't just free up 2 days right now for this.

**Comment by mariusandra** [comment]
The next steps from my side regarding "first event today" and "first time event tracker" are:
- Discuss within the team how we could implement "only if it's the first event" style filters into the trend and funnel insights.
- Discuss what is the overlap between that and cohorts in HogQL, which I always envisioned you could inline into insight filters.
- Actually finish the HogQL trends and funnels rewrite, making these new features possible.
- Implement what is needed so that those users (and many others) will be able to use the new system to query for the same data
- The "event sequence timer" use case is probably solved with similar methods. However it's also possible we could implement a bespoke SQL workaround for each of the 8 affected users.

With regards to the property flattener, the plan is:
- Improve the HogQL type system and JSON support until it's not horrible (treat every string as JSON, wrap strings with JSONExtractArrayRaw if passing them into a function that expects an array, etc)
- Migrate or ask to migrate users off of the old property names and onto the new ones.

**Comment by gregegan** [comment]
Following up here to see if any progress has been made on `First time event tracker` replacement feature?
