### ISSUE TITLE
Mega-ish issue 2024 Q2 - Content Plan for LLMs/AI

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#194]
Part of [Megaissue 2024 Q2 - Posthog for LLMs](https://github.com/PostHog/meta/issues/190) is to write SEO content for LLMs/AI. Below is the plan for the content I plan to write. The focus is around tutorials for product analytics with the different LLM/AI sdks that are out there

**LLMs**
- [x] https://github.com/PostHog/posthog.com/issues/8168
- [x] Tutorial: Anthropic's Claude analytics
- [x] Tutorial: Cohere analytics
- ~Tutorial: Meta Llama analytics (need to double check this)~
- ~Tutorial: Google's Palm analytics (need to double check this)~
- ~Tutorial: X's Grok analytics (need to double check this)~

**Image Generation**
- ~Tutorial: DALL-E analytics~
- ~Tutorial: Midjourney analytics~
- ~Turorial: Stable Diffusion analytics~

**Speech to Text**
- ~OpenAI Whisper analytics~
- ~AssemblyAI analytics~
- ~Deepgram analytics~

**Comment by Lior539** [comment]
cc @andyvan-ph @ivanagas for feedback

**Comment by ivanagas** [comment]
I'm not going to mince my words here, I don't think this works. 

1. All of these search terms have 0 searches.
2. Unlike frameworks, there isn't a big difference of implementation for all of these. From what I can tell, developers plug in different LLMs easily (using something like Langfuse). They basically just change the API endpoint they call but the output of that API says the same.
3. It doesn't seem like SEO is driving the growth of other companies in this space (like Langfuse)
4. I'm not sure when our ICP would search these terms. Most of the results are related to doing data analysis. Would they just Google "app analytics" or "framework analytics"?

I definitely think there is valuable SEO content and tutorials to be done for our ICP around LLMs. Some ideas I've found:

- langchain tracing (480/m)
- langchain alternatives (2400/m)
- llamaindex vs langchain (1900/m)
- Something around how analytics/PostHog can help with [RAG](https://www.promptingguide.ai/techniques/rag) or [evaluation](https://docs.llamaindex.ai/en/stable/understanding/evaluating/evaluating/)
- GPT Store entry of some kind: https://chat.openai.com/gpts
- Instead of X analytics, what if we try for "X API". Cohere API has 1k search/month. Do a example tutorial of setting it up and using it, and include PostHog analytics (sort of like Next.js cookie banner tutorial, get a high traffic keyword only slightly related)
- How analytics can support/connect to vector dbs like Weaviate and Chroma? No idea if this is possible or relevant.

**Comment by Lior539** [comment]
Thanks for the thoughts Ian! I agree with some of what you say. Following your feedback, I've updated the list to exclude Text-to-speech and Image apis, as I dont think those will get much search volume.

As for the LLMs, I still think they're worth doing. You may be right re your points 1-4, but I think the best way to tell is to write the posts and look at the results after publishing. And in any case they shouldn't take too long to write (probably about a week's worth of work). This way we'll at least have good data going forward

> I definitely think there is valuable SEO content and tutorials to be done for our ICP around LLMs. Some ideas I've found:

Thank you for these suggestions too. Im hesitant to write ones that don't have an analytics angle, since otherwise I don't think we'll be targeting the right users since theres not enough of an overlap between what they're searching for and what PostHog can do for thek. 

I'll dig deeper into the more analytics angles and see if there are topics to write about

**Comment by andyvan-ph** [comment]
> As for the LLMs, I still think they're worth doing. You may be right re your points 1-4, but I think the best way to tell is to write the posts and look at the results after publishing. And in any case they shouldn't take too long to write (probably about a week's worth of work). This way we'll at least have good data going forward

Is that a week each, or a week for all of them? If it's the former, I'd prefer shipping a couple and seeing how they do before committing to doing more. If the ChatGPT example, plus maybe one other, don't work then it's unlikely others will.

**Comment by jtemperton** [comment]
Yeah, agree testing it on one or two, taking some time to measure impact. Especially if we reckon the search volume is pretty low. It's also potentially more content to keep updated as functionality changes, etc.

**Comment by Lior539** [comment]
Closing out this Q2 issue. WIll create a new one for Q3. Ended up writing a bunch of content not on this issue
