### ISSUE TITLE
PostHog for Mobile 

### ISSUE THREAD

**Issue by Lior539** [PostHog/meta#217]
## Goal

- Increased adoption in our mobile SDKs, specifically by new org sign-ups

## Plan

Alternatives content:

- [x] UXCam (110/m) - @Lior539 
- [ ] [hotjar for mobile apps (260/mo)](https://posthog.slack.com/archives/C015CRUQR7Y/p1721124135054589) - @andyvan-ph 

Blogs:

(Will chat to Manoel for more ideas)

- [ ] Blog with Manoel on how we built mobile session replays (aim to get on hackernews) - @ivanagas 
- [x] Mobile app metrics to track (600/m, KD 9) @Lior539 
- [ ] Best mobile app _engagement_ metrics to track (maybe this is a tutorial) [(70/m, KD 28)](https://app.ahrefs.com/keywords-explorer/google/us/overview?keyword=app%20retention%20metrics)
- [ ] Best mobile app _engagement_ metrics to track (maybe this is a tutorial)
- [ ] Maybe: [Mobile app benchmarks](https://posthog.slack.com/archives/C015CRUQR7Y/p1720188695935179)
- [x] Best free and open source mobile analytics tools - @Lior539 
- [x] Best mobile app session replay tools ([20m, KD4](https://app.ahrefs.com/keywords-explorer/google/us/overview?keyword=mobile%20app%20session%20replay)) - @Lior539 

Tutorials:

- [x] How to set up iOS session replays - @Lior539 
- [x] How to set up Android session replays - @Lior539 
- [x] ~How to set up React Native session replays~ We dont support RN replays

Case studies:

- [ ] Two case studies featuring mobile-first customers

Housekeeping:

- [ ] Update existing alternatives+ in-depth guides to include mobile session replay (especially Logrocket,  fullstory, smartlook, who are the main session replay alternatives. Will need to to check the others too, though). @andyvan-ph 
- [ ] Update alternatives+ in-depth guides to include mobile analytics for mixpanel, amplitude, google analytics, smartlook, microsoft clarity (Biggest players in the space. Will need to to check the others too, though) @andyvan-ph 

Other ideas:

- [ ] Promote Posthog/blogs/the newsletter in mobile dev specific newsletters - @ivanagas 

## Related issues

- For writing session replay alternatives: https://github.com/PostHog/product-internal/blob/main/competitors/2023-07-11-mobile-recordings-research.md

**Comment by Lior539** [comment]
tagging @charlescook-ph @andyvan-ph @ivanagas @jtemperton for comment. 

This is a list to get us started, and we will probably add more items as we go along. Would love to hear your feedback, thoughts, ideas.

Also, curious to hear if you think we should do the "Posthog vs xyz"  guides, given they're usually quite high effort and the alternatives blogs cover similar content already (and are usually lower effort)

**Comment by marandaneto** [comment]
> PostHog vs Y

I'm usually not a big fan of articles such as X vs Y because it's always super biased for X or Y and most of the time the reader does not learn anything.

The type of content I "Manoel" like to read is when you learn something from it, an example:

An article explaining the importance of DAU/MAU for Mobile, then you teach how to install the PH SDK, how to capture the DAU/MAU data either automatically or manually, create the dashboard, and explain how to "read" the dashboard.

DAU/MAU is just an idea, the mobile dashboard has many other interesting insights: https://posthog.com/templates/mobile-dashboard, and of course we don't need to stick to those anyways.

> Blog with Manoel on how we built mobile session replays (aim to get on hackernews)

I also want to submit a talk with a topic around this technical challenge at conferences, so the blog post can be the first version of it.

> Promote Posthog/blogs/the newsletter in mobile dev specific newsletters

Yes, I know quite some, and I know Microsoft Clarity is already [promoting Replay for Mobile as well](https://androidweekly.net/issues/issue-629)

> Increased adoption in our mobile SDKs, specifically by new org sign-ups

I'd love to see some insights like this, the ratio of new mobile org sign-ups, or even existing orgs sending events/using feature flags, etc using the Mobile SDKs.
I tried to do that with Metabase already but Metabase isn't designed to read the data from all customers within more than a few days, the query just times out, we probably need to capture this info during events ingestion/flags evaluation, or find another way (happy to learn more from you all here).

**Comment by andyvan-ph** [comment]
- I'd say no to comparisons. There's no search demand for them yet and, as you say, alternatives cover most of the ground anyway.

- Big +1 to promotion in Android and iOS app newsletters. This phase is all about awareness and they're good for awareness if we can nail the messaging.

- I think we should go deep on tutorials. We know this works for us and plays to our strengths. What are the problems mobile devs trying to solve? What are they trying to track? How can they do that in PostHog? We should look beyond just mobile session replay.

- Since it's in the goals already, we can include a use case landing page. Assume at least one, though it might make sense to do separate ones for Android and iOS analytics. I will look into that.

- Migration guides? I suspect migrating from Firebase to PostHog could be a good one.

- I think we can include a paid ad component as well for awareness. Could be comparisons ads as an alternative to actual guides.

- I'd recommend using Ahrefs to do some competitive keyword analysis and see what they're ranking for. We don't necessarily want to do the same things, but will be useful context / inspo for ideas.

**Comment by charlescook-ph** [comment]
@robbie-c may have good ideas here as one of our resident mobile app experts!

**Comment by camerondeleone** [comment]
From a commercial standpoint, based on our experience with the Flurry sunsetting/migration, I would suggest not prioritizing that. I'm not sure we sold a single deal from it, and the mismatch in expectations/pricing were nontrivial. It's entirely possible some people migrated without taking the deal and self-served to high volume.

I've heard Firebase more often than I've heard Appsflyer on calls (contrary to industry numbers, but take w a grain of salt since this is not systematic). But some comparisons that explain the differences, and (without seeming too sales-y) justify the added value you'd get from PostHog commensurate w the increased cost, would be really helpful from my perspective. 

High volume mobile customers are ideal for us if we can get over the pricing hump, because users are mostly logged in (ie not personless), and the use cases lends itself to flags/a-b testing on top of analytics, which makes us much more sticky.

**Comment by ivanagas** [comment]
- "Best free and open source mobile analytics tools" blog: Similar ones are some of our best performing content, we don't rank here.
- Influencers: I've already started to reach out to some here, we might be able to capture some latent demand like we did with Theo and "google analytics alternatives"
- +1 to updating existing alternatives, session replay for X tutorials, no comparisons, 
- Rather than deep dive tutorials on specific problems, would be nice to have some SEO content related to mobile like the ones [I listed here](https://posthog.slack.com/archives/C015CRUQR7Y/p1718041332515459). I find that non-product, non-SEO tutorials don't drive a lot of impact. 
- Lets get some demand for a migration guide before we write them. 
- I can do newsletter ads, will take it out of existing newsletter ad budget
- Happy to help with Manoel's blog too

**Comment by andyvan-ph** [comment]
> "Best free and open source mobile analytics tools" blog: Similar ones are some of our best performing content, we don't rank here.

+1 to this. I'm sure there's search for android and iOS. Will hard to rank, but worth doing long-term anyway.

**Comment by robbie-c** [comment]
Some random thoughts:

* For React Native, Expo is a major player (I would not start a new react native app without using expo), and they already list us in the analytics tools section https://docs.expo.dev/guides/using-analytics/ . I would see if we could a more prominent position in their integration section, i.e. a top level page (which Firebase/Sentry/Supabase already have) given that we ar more than just analytics. They are a YC company so maybe James or Tim could reach out.
* I think comparing posthog analytics vs Firebase analytics could also be a comparison of all of our features vs Firebase, e.g. feature flags. E.g. my startup couldn't use Firebase's feature flags because they were missing some features that we do have at posthog (you couldn't do server-side evaluation of flags for a user, and there wasn't a way to create groups of users that always saw the same value for a flag).
* What would go into posthog vs appsflyer? Afaik the main selling point of appsflyer is their mobile attribution stuff (storekit integration etc) which we don't have yet
* I didn't know until I just googled it that Flutter had caught up with React Native's popularity, is there anything we can talk about there? <img width="1204" alt="Screenshot 2024-07-05 at 11 29 22" src="https://github.com/PostHog/meta/assets/2056078/71a2ebee-063f-4900-8d2b-5375db227e86">
* In terms of features, push notifications would be huge, I know it's being worked on. Auth / deep links / attribution / crash reporting would also be amazing

**Comment by Lior539** [comment]
Thank you everyone for the feedback:

- Removed in-depth vs guides
- Removed flurry (its shutting down)
- Removed appsflyer alternatives (It's more marketing attribution focused)
- Add case studies for mobile first customers
- Added a bunch of blogs

Note we already have a bunch of existing tutorials+blogs on mobile e.g. best mobile app ab testing tools

> I can do newsletter ads, will take it out of existing newsletter ad budget
Happy to help with Manoel's blog too

@ivanagas this sounds good. Since both of these go hand-in-hand (you could probably promote Manoel's blog in the newsletters?), is it okay if I assign both of these to you?

**Comment by marandaneto** [comment]
@Lior539 

> We dont support RN replays

hold my beer... https://posthog.com/docs/session-replay/react-native

**Comment by Lior539** [comment]
CLosing out as not focusing on this in Q4
