### ISSUE TITLE
Iceland March 2022 offsite retro

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/meta#42]
Please include your feedback for the offsite in this issue!

- What went well
- What could have been better
- Open questions/other comments

**Comment by charlescook-ph** [comment]
**Went well**
- Well-organized - felt seamless/low stress
- Sessions were all good and generally an improvement on Porto
- Lots of nice touches that made it feel special - merch, poster, careless whispers, certificates
- Lots of opportunities/breathing room to socialize in the schedule

**Could have been better**
- Would be good to have more opportunities to not eat at hotel (I only had 2 non-hotel meal opportunities)
- A quiz where one team couldn't dominate would have been more fun

**Open questions/points**
- How involved should folks who couldn't make it be - did we take the right approach in just sharing materials?
- Let's make sure we have good follow-up on all the sessions
- Keen to open source this when @postgrace is back

**Comment by clarkus** [comment]
Was anything documented for folks that weren't able to attend?

**Comment by jamesefhawkins** [comment]
I was really pleased with this offsite overall.

What went well

* Walking the line.
  * Was memorable and engaging.
  * Made me realize how I should be more empathetic.
* Hackathon
  * I particularly liked how useful most of the stuff is. I'm *very* excited to ship some of this stuff - multiple items could change the game for us.
  * Thought the process used to run it worked well.
  * Appreciated the energy people put in
 * Hotel
   * This worked way better than I thought. I was worried not having an entire place would make it lose the skill.
 * Not too many sessions
   * Sometimes I wonder if we bore people by doing too many sessions
* The 360 feedback gave me some useful things to improve.
* The first day was pretty cool - I liked doing a mild hike and the blue lagoon was good fun.
* Hotel was comfortable.
* Buses went in straight lines!
* I liked having a more detailed view of the stuff we want to build next. This will be handy when talking to investors/customers in future (even if we don't necessarily stick to it!)

 What could have been better
 
* The buffet meals got a bit repetitive by the end. That said, I think not having to wait around for service in restaurants was much better than not doing this. I also preferred buffet to table service for the same reason - feels more natural / conversation flows better.
* Got really hungry during day 1 of the hackathon. Maybe we should organise food to just arrive in future.
* Not sure I'd pick a cold weather place again. I missed having a pool and a little sunshine, but it was cool to try somewhere different.
* (So far) haven't done great at communicating to those not there, but I wouldn't want to compromise session quality by trying to have 2 way communication with people that can't attend - the whole point is to be present / not to feel like we're in a zoom meeting.

**Comment by tiina303** [comment]
#### What went well

* +1 Lots of opportunities/breathing room to socialize in the schedule
* During the issues discussion we split into groups based on where people wanted to be/work on, which was great as we had the motivation to figure something out (nit: we had 2 topics, and that still meant that not everyone was excited about both, maybe narrow down even further to 1 issue each small group). For context last offsite it was random groups looking into issues assigned to them.
* +1 Hotel was quite nice & I liked that we could eat there & that it was a buffet
* +1 not too much time spent on busses :D 
* People who live in the city of the offsite also have the opportunity to stay at the offsite location (was glad to be able to spend more time with Yakko, which otherwise could have been trickier)
* Hackathon was quite relaxed and folks were open to helping others outside of their hackathon team (really appreciated the help :) )

#### What could have been better

* +1 to avoiding cold weather - would like a pool & sunshine (maybe just have the 1 big company offsite in the summer or in the southern hemisphere next year)
* +1 Jeopardy didn't have the best participation options for everyone

#### Open questions/other comments

* I was hoping we'd talk more about support and future plans with that (e.g. maybe pre-offsite we could all propose topics and vote on them and the one winning topic gets a session on its own):
    * in the engineering offsite the answer was basically: "this should be discussed with everyone at the company"
    * support hero load is quite high & stressful for some folks
    * there's multiple places we need to watch: papercups and/or community slack & other slack channels, website questions, issues in repos
    * stuff gets dropped, e.g. the 9k issues in posthog/posthog
    * stuff doesn't reach people it should, e.g. there were a bunch of ingestion issues that I discovered (and changed our prioritization based off of) from previous weeks because I was support hero
* +1 How involved should folks who couldn't make it be 
    *  maybe we could film the presentation/conclusion part of sessions next time, so the ones who couldn't make it could get the context
* +1 Maybe we should organise food to just arrive in future. Especially during the hackathon it would have been nice to have easy/fast food access.

**Comment by joethreepwood** [comment]
To me, everything went well with one exception. I was skeptical that a hotel would be a good venue for us, but it worked perfectly and Grace & Charles did a fantastic job with organisation. 

The exception is the cross the line activity, which I have very strong feelings about. I recognise it was well-intentioned and isn't something we plan to repeat, but I ultimately found it harmful, divisive and inappropriate. I wanted to explain why in a bit of detail, as it's been a frequent topic of discussion since.

As this is a public issue, I'll refrain from mentioning any individuals specifically but I am willing to have a longer discussion on this privately. 

- **Why was this activity harmful for me?** For me it bought up a lot of deep-seated emotional topics and traumas which I then felt I had to reconcile alone, needlessly. We were asked to confront/expose issues such as suicide, domestic violence and sexual identity, but without help moving forward afterwards. No counselling was available and we were in a strange environment away from usual support networks such as friends, families or therapists. The debrief was very limited and I purposefully chose to stay silent because I felt discussion of my feelings -- which were of _intense_ shame, sadness and isolation -- would exacerbate them and create further division for myself and others. This activity also complicated feelings following the 360 feedback session and left me feeling unable to be fully present for the rest of the offsite. I dread to think what a worst possible case could have been for people with deeper mental health struggles.

- **Why do I feel this activity was divisive?** Because the activity was done in silence and without an appropriately structured debrief meant I felt it separated everyone into binary groups and cliques. A takeaway comment for me was from one (again, well-intentioned and kind) co-worker admitting that they had to consciously walk-back judgement of others. I didn't feel we were closer afterwards; I felt we were farther apart and that (because of, for example, the political lines drawn and managers present) it may not even have been safe for me to disclose some things. I don't feel entirely safe sharing this feedback either. The format prevented me from giving context and, while we were advised beforehand that stepping forward is voluntary, this overlooks the fact that _not_ stepping forward create as much a division as doing so. I chose to be 100% transparent, but a question toward the end of the activity made it clear that not everyone did the same.

- **Why do I feel this activity was inappropriate?** Many of the topics which came up would have been illegal if they had been asked in an interview or other context. It would not be appropriate for me to ask any of my colleagues (let alone ones I'd only ever met once, if at all) if they'd ever had suicidal thoughts, so I don't feel it's appropriate to ask _all_ of us those questions. I disclosed that I had previously questioned my sexual identity, for example. There's context to this; but why should I feel pressured to share it in the workplace? The risk of conflict for individuals _and_ the company are also numerous. What do I do if I disclose I'm a divorced atheist who has questioned their sexual identity and my manager is a right-leaning Christian? Should I now worry about how this will affect my performance reviews? If I'm dismissed badly tomorrow, can I cite this as cause and bring action against the company? What are managers expected to do with the information they discover? I'm still not sure why we felt this activity was useful or what we hoped to gain. Our values explicitly say we are 'a team, not a family'. 

Again, I know the activity may have been well-intentioned, but I'd strongly urge us not to run activities like this again without serious consideration of the need for it and the impact on individuals. It's taken me several days of holiday (during which I've felt unable to fully disconnect) to start feeling better and while I don't believe it's going to impact my work when I return to 'the office' tomorrow, it certainly impacted my offsite experience.

**Comment by postgrace** [comment]
**Went well**
- Iceland was a really unique place to host an offsite, and will definitely be a selling point for candidates who check us out
- I felt that the schedule was a good balance between sessions, free time, and fun activities
- The Fosshotel was a good choice for a couple of reasons
1. They were very flexible on room cancellations and were receptive to making the conference room feel less corporate and more welcoming
2. Having the beer garden on-site made our evening hangouts really easy and prevented me from having to buy alcohol separately for the team (which is surprisingly difficult to do in Iceland)
3. Breakfast was delicious and had a great variety
4. It was really helpful to have coffee/tea and afternoon snacks in the conference room

- The coach bus to and from the Volcano and the Blue Lagoon was super smooth and timely
- I thought the Blue Lagoon was a solid team outing with very little planning or overhead on my part
- @lottiecoxon really pulled out all the stops on merch, certificates, and the banner; it made the whole event feel special
- Doing session reviews before the offsite was helpful in ensuring a high level of quality
- Food and drinks at Lebowski bar were really good
- I thought the Careless Whispers activity was really well-received and it was great that folks contributed to envelopes for people who couldn't make it
- I really enjoyed @joethreepwood DJing during the hackathon

**Could have been better**
- Iceland is the third most expensive country in the world, so we definitely spent a lot more on this offsite than we would have somewhere more reasonable. It was also freezing cold and was a disincentive for folks to leave the hotel
- I didn't find Reyjavik to be a very engaging city to explore
- I wish the Fosshotel would have been more transparent about Haust being the same buffet night after night; had I known, I definitely would have had us dine elsewhere for a number of the meals
- Yoga was pretty poorly attended, and I think we should consider whether something like this is worthwhile next time (or look within the team to see if someone is willing to facilitate)
- It was probably unnecessary to buy so many snacks from Costco in addition to the snacks we bought through the hotel
- Getting merch into Iceland is a nightmare; would be worthwhile to see if we can ship to teammates and have them check boxes on their flights rather than trying to ship to our destination (I did this with the hats and scarves and paid $0 duty)
- We should find a way to have non-technical folks engage more deeply with the Hackathon, or plan an alternative activity for them
- We should book all offsite flights as refundable/with cancellation insurance, especially during COVID, as I'm sure we lost a lot of money on late drop-offs
- Buying FlyBus tickets ahead of time was a bit of a mess due to late cancellations; we probably should have bought them upon arrival individually to save costs
- Reflecting deeply on @joethreepwood 's Cross the Line feedback, this was a huge learning moment for me, and I think we could have avoided some of the negative fall-out from the activity through the following:
1. I should have followed my own guidance and run through the whole activity and list of questions with someone else such as @charlescook-ph to vet the subject matter and possibly adjust the list further than I already had using my best judgment. I intentionally did not do this because I wanted as many people to participate as possible without prior expectations, but this was a mistake.
2. I should have provided specific trigger/content warnings about the subject matter of all of the questions to allow folks the chance to properly consider an opt-out, especially as I had never facilitated an intense activity like this with our group 
3. I should have spoken with managers about the intensity of the activity, and run a training session on how best to debrief and support team members who may have been negatively impacted. I intentionally planned the schedule to allow for free time afterward to decompress, but folks naturally moved right into hacking, which I could have predicted. A better approach would have been to break into smaller groups to have a facilitated conversation led by managers, followed by at least an hour of free time to decompress.
4. I should have been more mindful of the differences in expected workplace cultures/environments as part of such an international team. Just because I have successfully facilitated this in the past with US-based teams, doesn't necessarily mean that it will be well received by a more culturally diverse group of people.
5. I should have found a way to participate myself to offer mutual insight into my lived experience

- The layout of the Lebowski bar was quite weird, and not very conducive to a 30 person group
- A primer on how Jeopardy works would have made the activity run more smoothly, and I should have been more thoughtful with the question categories and teams to even the playing field a bit. Prizes would have also been nice to offer
- I think having a running quote wall would have been a nice passive activity
- The Hedinn restaurant where the app/platform team went was a lot fancier and more expensive than I expected
- Echoing above, we should have pre-planned food during the hackathon
- I was unaware that Lyft/Uber aren't in Iceland, and should have checked this ahead of time

**Open questions/points**
- I'm rounding up the final budget numbers and will share this with the team by the end of the week
- I will be open-sourcing the planning timeline and all of the templates I created so we can hopefully put Flok out of business ;)

**Comment by postgrace** [comment]
Here is the [budget round-up](https://docs.google.com/spreadsheets/d/1re6gNo1SFrXklb7lp1oPWtkelG4q_ZP-G19sE4bMBlQ/edit?usp=sharing).

**Comment by yakkomajuri** [comment]
@postgrace the above link is accessible to anyone - is that expected?

**Comment by postgrace** [comment]
@yakkomajuri I defaulted to keeping it public for transparency, but if someone has concerns with that let me know and I can make the link only accessible to the teamn.

**Comment by yakkomajuri** [comment]
Very nice!
