### ISSUE TITLE
Retro: Launch Week 1

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/meta#43]
We ran our first [Launch Week](https://posthog.com/blog/launch-week-universe-of-new-features) from March 21st-25th this year. 

Please share your feedback in this public Issue, namely:
- What went well
- What could have been better
- Open questions and ideas for next time

**Comment by jamesefhawkins** [comment]
# What went well

- We got a bunch of functionality out of the door in a short space of time.
- We shipped it, and can learn from it.

# What could have been better

- Not much engagement from people outside of our own team.
- Didn't really get _everyone_ involved (especially me and the customer success team IMHO). I think we captured about 65% of the stuff the company is working on. Specifically, we were trying to get Squeak! out as a growth-oriented product, and we coudl have used the customer success team to get existing customers more excited 1/1

# Open questions and ideas for next time

If app team feel this helped them, then I'd be happy to repeat and would aim that the entire company is more focussed on this.

If the app team didn't feel this made much difference, I'd propose either (i) not doing this again, due to low external engagement or (ii) having a very different way of building hype / engagement from what we did this time

**Comment by charlescook-ph** [comment]
**Went well**
- Company aligned around shipping a lot of great product work.
- Lots of high quality content from a range of team members, inc. engineers.
- Pushed us to fix a lot of things like Docs and updating the Website product pages.
- Lots of awareness, including a viral HN post from @macobo (over 5k views) and 773k Twitter impressions for reasonable spend. 

**Do better**
- Bucketed under 'it didn't generate that much external hype otherwise':
  - It didn't generate a record week of signups (415 vs. 446). Did we fail, or was signups not the right target metric? 
  - We didn't succeed in doing any community type stuff like a HogTalk - we couldn't secure a speaker. 
  - More cross-promo with other companies to get the word out, retweets etc. would have helped. 
- Product release for self-host customers missed the launch week (though I think impact was minor tbh). 

**Open questions**
- The big one - should we do this again for ~plugins~ apps? This is a whole-product initiative rather than a marketing one, so it would be good to get wider feedback on this.

**Comment by joethreepwood** [comment]
**Went good**
- Got something out every day
- Hackernews post
- Got lots of internal engagement during production

**Could have gone gooder**
- No real external hype or engagement (1)
- Did not really line up with the actual release of promised features (2)
- Fact that (2) didn't result in mass confusion is indicative of the scale of (1)

**Ideas**
- Sign-ups does feel like the wrong metric, as I don't think anyone will sign-up to PostHog just because we have a data management suite. Better metric: Github stars as indicator of excitement. 
- If GitHub stars is the metric, plugins could make a good topic for the future. 
- If we were to repeat this, I think we need a clearer idea of promotion for each day beyond simple social posts. E.g. We need to be bringing in influencer support, driving to a clear goal. 
- Weird idea: "When we get to X Github stars, we'll do Launch Week 2!". Track this openly with a star-meter. 
- We could probably do a better job of reporting success internally each day. It felt at times like we were ticking boxes, then on to the next one without sharing excitement around the launch.

**Comment by andyvan-ph** [comment]
Putting in writing what I mentioned in sprint meeting, namely that one of / the main metric ought to be usage / awareness of the features we're announcing / promoting. This isn't exclusive to launch weeks, obviously, and basically agree that we should over commit to them or rule out doing another in future. Launch weeks and option, not a necessity.
