### ISSUE TITLE
Ideas to commemorate Pride Month

### ISSUE THREAD

**Issue by charlescook-ph** [PostHog/meta#46]
June is Pride month in a few countries, including the USA and UK. It would be nice to tie some of our ongoing activities to a theme of supporting the LGBT+ community as part of making PostHog an inclusive company. 

Here are 3 simple proposals:

- [External] Financially supporting relevant organization(s) - we already support [Django Girls](https://djangogirls.org/en/), so we could find another couple of organizations (and do a bit of co-marketing around it). 
- [External] PrideHog - @lottiecoxon I'm not _exactly_ sure what this means, but usually the idea follows the visual for me... maybe PrideHog features in all our blog artwork in June @andyvan-ph?
- [Internal] BookHog - June's book choices will be LGBT+ themed. Suggestions welcome. 

Happy to take any feedback on this of course - trying to go for actionable > perfect and then iterate (as is PostHog tradition, of course), but feel free to suggest additions/alternatives!

**Comment by lottiecoxon** [comment]
We could incorporate rainbow flags/colours on the site and app as well as maybe adding some pride accessories to the hedgehogs already on the landing page?

**Comment by clarkus** [comment]
Incorporating flags/colors can be cool, but I fee like we have to walk a fine line there. So many companies do this and it just feels performative and self serving. I know that's not our intent and that our motivations are good, I just want us to be purposeful and thoughtful with how we incorporate these things into our brand even on a temporary basis. 

I love the idea of donating to groups who are actively working to support their communities. Leading with thoughtful actions like that seems like a great idea. Another thing to consider would be recurring support outside of pride month. These groups are working all the time, so it could mean a lot to help fund them during a non-prime giving times. 

Like this idea and would love to contribute in some way if there's a need. ❤️

**Comment by joethreepwood** [comment]
I like the idea of these long-running sponsorships because it means we don't run the risk of doing stunty, performative stuff in the future. Instead, we can revisit organizations we already sponsor and ask them to work with us on some sort of spotlight content. It's a much more meaningful and authentic message than a one-off. 

In the nearer term, foundation-wise we could consider the [LGBT Foundation](http://lgbt.foundation/), though it isn't specific to engineering. There's also [Lesbians In Tech](https://lesbianswhotech.org/pridesummit2022/) and [Ostem](https://ostem.org/) which are a little more focused. 

We could also host a HostHog and invite members of the community to that, if there's a particular speaker we could consider?

**Comment by charlescook-ph** [comment]
Nice, thanks for this! Would only suggest a couple of tweaks, but otherwise I think this is a great program:

- Week 2: I'd vote for Disclosure, seems more global in focus. Will we have time for a conversation after?
- Week 3: as we already have a good program of activities, I'd skip the presentation as I think we can cover this in BookHog - I wanted to propose we read either [The Stonewall Reader](https://www.goodreads.com/en/book/show/42377825-the-stonewall-reader) or [Pride](https://www.goodreads.com/en/book/show/52758762-pride), both of which cover historical topics. 
- Support: I think having a monthly donation that depends on attendance is cool, but let's be specific($10 per month per person that attends?). I also think we should support a charity instead though that is a bit more closely connected to PostHog's mission - e.g. [TransTech](https://transtechsocial.org/) or Lesbians Who Tech. Obviously there are many many worthy causes we could support, but something closer to our mission feels more authentic.

**Comment by corywatilo** [comment]
I really want to caution us against too much social advocacy, and any we do implement is optional and not forced. We need to walk a line between being inclusive and pushing any specific agenda.

When we talk about changing colors of assets to rainbows, it’s not only self-serving but is pure virtue signaling, and I agree it's overplayed.

Anyone can see in our handbook that we’re an incredible inclusive company, and I'm super proud of that. But the line needs to be drawn in the sand at using our brand for social advocacy.

I don’t see a problem with having voluntary sessions to discuss topics, but it’s also worth remembering the reason we’re at PostHog is to build a successful product and company, and to produce a return for our investors.

Moreover, this heavy-handed approach to pushing an agenda can end up being a major red flag to the large pool of candidates who are looking to work in a place not mired in social issues. (I’d lump myself into this pool. I’m here to build the coolest company to date in my career, and one of the things that drew me to PostHog is that it didn’t feel like I can come with a potentially different perspective and could fit in - true diversity.) This is especially true for older candidates, and having too much of this will push them away, as they tend to bring a different perspective than those who have entered the workforce within the past decade. We will ultimately need these people as we continue to grow as a company.

We’ve seen several large startups who have pushed back against social advocating on company time because it ends up becoming such a divisive problem, and while it might not be the perfect example for us, I think it’s closer to the right approach.

We talked about it a bit at the offsite, but true diversity is more than just a handful of issues that make the headlines. I would continue to encourage us toward being neutral around any personal perspective, opinion, or ideology, as it will continue to help us create the most inclusive work environment we can, and ultimately that’s what we’re trying to create.

**Comment by postgrace** [comment]
@lottiecoxon and I just had a great catch-up to brainstorm on more ideas for next month and we think we found a good idea that will help us hit two birds with one stone.

Besides me, there is a whole class of queer folks who are Edie Wilson coding scholars sponsored by Lesbians Who Tech, and we had the idea of sending each of them a PostHog merch pack, possibly with a PrideHog sticker, to introduce them to the company and celebrate the month.

This is beneficial for a few reasons:

- All of these people will be graduating from coding bootcamps in the next year, and this will encourage them to connect with PostHog for possible career opportunities (we could even encourage them to contribute to open source projects as part of their learning journey)
- It'll help us clear out some of the old merchandise that has been sitting in the store so we can make way for fresher merch drops in the future

**Comment by clarkus** [comment]
> I don’t see a problem with having voluntary sessions to discuss topics, but it’s also worth remembering the reason we’re at PostHog is to build a successful product and company, and to produce a return for our investors.

I don't see how these are at odds. We regularly learn about each other via life stories and other more socially-driven presentations, and this just feels like a more purposeful and outward focused take on this. Personally, I would love to learn more about other's perspectives and life outside of work. Being fully remote means that we don't get a lot of opportunities to learn about each other. 

> This is especially true for older candidates, and having too much of this will push them away, as they tend to bring a different perspective than those who have entered the workforce within the past decade. We will ultimately need these people as we continue to grow as a company.

This feels like an assumption to me. I think I'm one of the older people at the company and I don't feel alienated or otherwise put off by this kind of action. If anything, it makes me feel even better about working here. 

> I would continue to encourage us toward being neutral around any personal perspective, opinion, or ideology, as it will continue to help us create the most inclusive work environment we can, and ultimately that’s what we’re trying to create.

I don't understand how neutrality fosters inclusion. I feel like acceptance and engagement drive inclusion. You can't really include folks if you don't know about them. Discussing this stuff is healthy and beneficial, and while I see how it might lean into distraction-from-work territory, these events are optional and up to personal discretion to attend. 

I like that we're making opportunities for this and hope that we can do more in the future.

**Comment by charlescook-ph** [comment]
> I really want to caution us against too much social advocacy, and any we do implement is optional and not forced.

Just want to cover this specifically: I think what we're proposing here feels appropriate - I don't see a risk of us being divisive/company-damaging or creating a big distraction for folks from building PostHog into an awesome company. 

On a scale of 1-10, I'd consider these activities to maybe be a 2 or 3 (where we're currently at 0). I don't think anyone is proposing going full Ben & Jerry's here, but rather creating an opportunity for folks to engage with these topics in a fairly basic and optional way.

**Comment by postgrace** [comment]
If anyone is curious, here are examples of how shifting to a completely apolitical company culture turned out for [Basecamp](https://techcrunch.com/2021/04/30/basecamp-employees-quit-ceo-letter/), [Coinbase](https://www.forbes.com/sites/rachelsandler/2020/10/08/60-employees-leave-coinbase-over-ceos-pledge-to-be-apolitical/?sh=321f47245a06), [Google](https://www.latimes.com/business/technology/story/2019-11-06/google-employee-walkout-tech-industry-activism), [Netflix](https://www.theguardian.com/media/2021/oct/20/netflix-employees-activism-walkout-dave-chappelle-controversy), and [Facebook](https://www.theverge.com/interface/2020/6/1/21276969/facebook-walkout-mark-zuckerberg-audio-trump-disgust-twitter).

**Comment by joethreepwood** [comment]
Just want to add a specific +1 to Chris' points and add some of my own.

> I would encourage us toward being neutral around any personal perspective, opinion, or ideology...Moreover, this heavy-handed approach to pushing an agenda can end up being a major red flag

I strongly disagree with the idea that we achieve neutrality by this, or that neutrality is even possible. 

Every decision anyone ever makes is a political act and we should recognize that choosing _not_ to champion an agenda will still express an opinion. We can choose to be social advocates on this topic, or we can choose not to be - but it's a choice either way and the idea that we remain neutral is neither practical, nor sustainable. 

Moreover, I also don't think neutrality is conducive to building a strong brand or that we do best for investors by refusing to take an opinion on things for fear of creating red flags. This is one of the reasons we _strive_ to be opinionated in our marketing content.

> This is especially true for older candidates...We will ultimately need these people as we continue to grow.

As one of the oldest people in the company (What's that on the horizon? Oh, it's my 40s!), I also do not feel this way. This argument also overlooks that _younger_ candidates may not feel this way and that we need those people too. In fact, we'll need them more and, bluntly, for longer.  

> Anything we do implement is optional and not forced...True diversity is more than just a handful of issues that make the headlines...[candidates may look] to work in a place not mired in social issues.

I do, however, strongly agree with Cory on this. We should aspire to be impactful and authentic, as well as respectful of those who do not wish to engage or want to engage in a different way. Attendance should be voluntary. We should take an approach which is holistic of our wider beliefs as an organization and isn't purposelessly heavy-handed. 

Personally, I think we can best do this by focusing on how these issues intersect with technology and by using transparent frameworks which focus on the experiences of individuals. Some of the ideas suggested above (Hogtalks, life stories, support for organizations like Lesbians Who Tech) feel like they meet this criteria. Others (screening documentaries without discussion, redesigning our mascot, supporting broadly purposed charities) do not. 

All of this is just my opinion however and I'm happy to take feedback on it.

**Comment by joethreepwood** [comment]
> * _Redesigning our mascot_ - this would be very much in keeping with PostHog's brand, given Max gets a new outfit every week or so. I don't see what the big deal is, unless the PrideHog being conceived here is something very different to BjorkHog, InspectorHog, CheerHog etc.? (I'm assuming this is for things like Grace's blog post).

Kind of? If we're introducing a new one for a blog image in a blog on this topic, that feels fine and in keeping with our approach. My assumption was that we may update other hogs across the site, for example on the homepage, with 'PrideHog' - and that feels less fine and veru performative logo-change. Happy to be wrong on this!

> * _Supporting broadly purposed charities_ - to clarify, do you mean we should consider a more specific charity than [Transtech](https://transtechsocial.org/), or are you referring to the original options presented before?

Yeah, I was referencing the original options. Transtech feels very relevant to our brand and mission.

**Comment by postgrace** [comment]
Agreed on all fronts @joethreepwood. Big +1 to having a discussion associated with all presentations/documentary showings! Education without conversation isn't very impactful in my experience.
